-- MySQL Script generated by MySQL Workbench
-- Fri Sep  9 13:23:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petscare1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `petscare1` ;

-- -----------------------------------------------------
-- Schema petscare1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petscare1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `petscare1` ;

-- -----------------------------------------------------
-- Table `petscare1`.`clinica_veterinaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`clinica_veterinaria` (
  `nit_cv` BIGINT NOT NULL,
  `correo_cv` VARCHAR(255) NOT NULL,
  `direccion_cv` VARCHAR(255) NOT NULL,
  `estado_cli` INT NOT NULL,
  `foto_clinica` VARCHAR(400) NOT NULL,
  `nombre_cv` VARCHAR(255) NOT NULL,
  `password_cv` VARCHAR(255) NOT NULL,
  `tarifa_cli` VARCHAR(255) NOT NULL,
  `telefono_cv` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nit_cv`),
  UNIQUE INDEX `UK1pwft6d445cjk1u5clv9v59n5` (`correo_cv` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`veterinario` (
  `documento_vt` BIGINT NOT NULL,
  `apellido_vt` VARCHAR(255) NOT NULL,
  `correo_vt` VARCHAR(255) NOT NULL,
  `especialidad_vt` VARCHAR(255) NOT NULL,
  `estado_vt` INT NOT NULL,
  `foto_veterinario` VARCHAR(400) NOT NULL,
  `nombre_vt` VARCHAR(255) NOT NULL,
  `password_vt` VARCHAR(255) NOT NULL,
  `sexo_vt` VARCHAR(255) NOT NULL,
  `telefono_vt` VARCHAR(255) NOT NULL,
  `clinica_nit` BIGINT NOT NULL,
  PRIMARY KEY (`documento_vt`),
  UNIQUE INDEX `UK2ev3m10iwldje6703qsddgbpt` (`correo_vt` ASC) VISIBLE,
  INDEX `FK33jdt3h77r3j937ogsqp44waw` (`clinica_nit` ASC) VISIBLE,
  CONSTRAINT `FK33jdt3h77r3j937ogsqp44waw`
    FOREIGN KEY (`clinica_nit`)
    REFERENCES `petscare1`.`clinica_veterinaria` (`nit_cv`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`usuarios` (
  `documento_usu` BIGINT NOT NULL,
  `apellido_usu` VARCHAR(255) NOT NULL,
  `correo_usu` VARCHAR(255) NOT NULL,
  `estado_usu` INT NOT NULL,
  `foto_usu` VARCHAR(400) NOT NULL,
  `nombre_usu` VARCHAR(255) NOT NULL,
  `password_usu` VARCHAR(255) NOT NULL,
  `sexo_usu` VARCHAR(255) NOT NULL,
  `telefono_usu` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`documento_usu`),
  UNIQUE INDEX `UKnvtftbkt9bp9ly5qlig49e6i6` (`correo_usu` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`agenda_cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`agenda_cita` (
  `codigo_agen` BIGINT NOT NULL AUTO_INCREMENT,
  `estado_agenda` INT NOT NULL,
  `fecha_agenda` VARCHAR(255) NOT NULL,
  `hora_inicio` VARCHAR(255) NOT NULL,
  `hora_salida` VARCHAR(255) NOT NULL,
  `notas` VARCHAR(255) NULL DEFAULT NULL,
  `documento_us` BIGINT NOT NULL,
  `documento_vt` BIGINT NOT NULL,
  PRIMARY KEY (`codigo_agen`),
  INDEX `FKoojoik91e9jpqu3vk4f2r2gy7` (`documento_us` ASC) VISIBLE,
  INDEX `FK83vxldbsdhs4qavxebgarqcte` (`documento_vt` ASC) VISIBLE,
  CONSTRAINT `FK83vxldbsdhs4qavxebgarqcte`
    FOREIGN KEY (`documento_vt`)
    REFERENCES `petscare1`.`veterinario` (`documento_vt`),
  CONSTRAINT `FKoojoik91e9jpqu3vk4f2r2gy7`
    FOREIGN KEY (`documento_us`)
    REFERENCES `petscare1`.`usuarios` (`documento_usu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`clinica_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`clinica_roles` (
  `clinica_nit` BIGINT NOT NULL,
  `rol_id` BIGINT NOT NULL,
  PRIMARY KEY (`clinica_nit`, `rol_id`),
  INDEX `FK543p21wdlgg48x2d4ha41gfky` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `FK543p21wdlgg48x2d4ha41gfky`
    FOREIGN KEY (`rol_id`)
    REFERENCES `petscare1`.`roles` (`id`),
  CONSTRAINT `FK636vir0dalp1dqmwqy2ui26fm`
    FOREIGN KEY (`clinica_nit`)
    REFERENCES `petscare1`.`clinica_veterinaria` (`nit_cv`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`horarios` (
  `id_horarios` BIGINT NOT NULL AUTO_INCREMENT,
  `dia_horarios` VARCHAR(255) NOT NULL,
  `hora_inicio` VARCHAR(255) NOT NULL,
  `hora_salida` VARCHAR(255) NOT NULL,
  `documento_vt` BIGINT NULL DEFAULT NULL,
  `nit_clinica` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_horarios`),
  INDEX `FK6dsa4oftyw7ay1jqfeu8nidaw` (`documento_vt` ASC) VISIBLE,
  INDEX `FK5m32i6q1r70c01lllopwpndws` (`nit_clinica` ASC) VISIBLE,
  CONSTRAINT `FK5m32i6q1r70c01lllopwpndws`
    FOREIGN KEY (`nit_clinica`)
    REFERENCES `petscare1`.`clinica_veterinaria` (`nit_cv`),
  CONSTRAINT `FK6dsa4oftyw7ay1jqfeu8nidaw`
    FOREIGN KEY (`documento_vt`)
    REFERENCES `petscare1`.`veterinario` (`documento_vt`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`keytemporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`keytemporal` (
  `keyusu` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`keyusu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`mascotas` (
  `codigo_mc` BIGINT NOT NULL AUTO_INCREMENT,
  `color_mc` VARCHAR(255) NOT NULL,
  `discapacidad_mc` VARCHAR(255) NOT NULL,
  `edad_mc` VARCHAR(255) NOT NULL,
  `foto_mascota` VARCHAR(400) NOT NULL,
  `nombre_mc` VARCHAR(255) NOT NULL,
  `peso_mc` DOUBLE NOT NULL,
  `raza_mc` VARCHAR(255) NOT NULL,
  `sexo_mc` VARCHAR(255) NOT NULL,
  `tipo_animal_mc` VARCHAR(255) NOT NULL,
  `documento_usu` BIGINT NOT NULL,
  PRIMARY KEY (`codigo_mc`),
  INDEX `FK24ioyiwchrwswbcijypqnf3r0` (`documento_usu` ASC) VISIBLE,
  CONSTRAINT `FK24ioyiwchrwswbcijypqnf3r0`
    FOREIGN KEY (`documento_usu`)
    REFERENCES `petscare1`.`usuarios` (`documento_usu`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`usuario_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`usuario_roles` (
  `usuario_doc` BIGINT NOT NULL,
  `rol_id` BIGINT NOT NULL,
  PRIMARY KEY (`usuario_doc`, `rol_id`),
  INDEX `FKbt9i9yrb9ug88xnh82n9m60pr` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `FK391y02554swuf6k97yamgpww6`
    FOREIGN KEY (`usuario_doc`)
    REFERENCES `petscare1`.`usuarios` (`documento_usu`),
  CONSTRAINT `FKbt9i9yrb9ug88xnh82n9m60pr`
    FOREIGN KEY (`rol_id`)
    REFERENCES `petscare1`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petscare1`.`veterinarios_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petscare1`.`veterinarios_roles` (
  `veterinario_doc` BIGINT NOT NULL,
  `rol_id` BIGINT NOT NULL,
  PRIMARY KEY (`veterinario_doc`, `rol_id`),
  INDEX `FKgxkh4ukwvbtpg9ywpupwfrfjr` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `FK4k998hloy8d6g58cnoq9rpfam`
    FOREIGN KEY (`veterinario_doc`)
    REFERENCES `petscare1`.`veterinario` (`documento_vt`),
  CONSTRAINT `FKgxkh4ukwvbtpg9ywpupwfrfjr`
    FOREIGN KEY (`rol_id`)
    REFERENCES `petscare1`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
